name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: test
        run: |
          echo '========================='
          echo "${{ github.event.release.tag_name }}"
          echo '========================='
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref:


